server:
        port: 8080
        servlet:
                context-path: /demoMoMo

spring:
        datasource:
                url: "jdbc:mysql://localhost:3306/momoDb"
                username: root
                password: root
                driver-class-name: com.mysql.cj.jdbc.Driver
        jpa:
                hibernate:
                        ddl-auto: update
                show-sql: true

momo:
        momoApiUrl: "https://test-payment.momo.vn/v2/gateway/api/create"
        secretKey: "K951B6PE1waDMi640xX08PD3vg6EkVlz"
        accessKey: "F8BBA842ECF85"
        returnUrl: "https://localhost:5001/Home/PaymentCallBack"
        notifyUrl: " https://dbab-125-235-239-167.ngrok-free.app/demoMoMo/bills/{{id}}/momo-callback"
        partnerCode: "MOMO"
