server:
        port: 8080
        servlet:
                context-path: /demoMoMo

spring:
        datasource:
                url: "jdbc:mysql://localhost:3306/momoDb"
                username: root
                password: Admin@123
                driver-class-name: com.mysql.cj.jdbc.Driver
        jpa:
                hibernate:
                        ddl-auto: update
                show-sql: true

momo:
        momoApiUrl: "https://test-payment.momo.vn/v2/gateway/api/create"
        secretKey: "K951B6PE1waDMi640xX08PD3vg6EkVlz"
        accessKey: "F8BBA842ECF85"
        returnUrl: "http://localhost:5173/payment"
        notifyUrl: "https://e581-2405-4802-80e5-f930-6165-c94d-3821-aa0a.ngrok-free.app/demoMoMo/bills/{{id}}/momo-callback"
        partnerCode: "MOMO"
